# Generated by Django 6.1.1 on 2026-09-28 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=200)),
                ('destino', models.CharField(max_length=200)),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('estado', models.CharField(default='CREADO', max_length=50)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
