# Generated by Django 6.1.1 on 2026-09-28 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='medio',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='pedido',
            name='motivo',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
